[Settings]
ID = "f82dec38-ec91-40c9-a1ca-ef20d915f1d3"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "game/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "game/build/"
  # This will be your default build command
  command = "yarn build"
